### ISSUE TITLE
add player rep system

### ISSUE THREAD

**Issue by neekly** [Rubberbandits/zonecontrol#27]
tied to your PDA login, killing players yields x points to the primary PDA, npcs yield configurable points, GMs can add/remove points

**Comment by Rubberbandits** [comment]
Players earn XP by:

Trading in mutant parts to NPC
Trading in faction patches to NPC
Revealing artifacts with their detectors
Gamemaster command

**Comment by grnadiac** [comment]
Can NPC stalkers on PDA be made to discriminate rank when making comments about specific players? IE certain messages would only apply to characters with specific stalker rank thresholds. "John Rookie is new around here, he's not gonna last." or "I think I just saw Jimmy Legend. I can't believe it..."
